### ISSUE TITLE
 rpmlib(PayloadIsZstd) = 5.4.18-1 is needed

### ISSUE THREAD

**Issue by dongbin86** [cat-in-136/cargo-generate-rpm#104] opened 2024-04-02 15:59 UTC
hi, I successfully created a rpm package ,but an error occured when I install that rpm package in centos7

error: Failed dependencies:
        rpmlib(PayloadIsZstd) = 5.4.18-1 is needed by polly-agent-0:0.1.0-1.x86_64

how to fix this problem ?

**Comment by cat-in-136** [comment] 2024-04-02 23:13
Set compression type as written in README.md.

> For the legacy system (e.g. centos7), specify legacy compress type explicitly e.g. `--payload-compress none`.

**Comment by cat-in-136** [comment] 2024-04-09 23:35
duplicate of #30

**Closed by cat-in-136** 2024-04-09 23:35 UTC
Labels: duplicate
